// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gjztnnhsfkbqxkwkbxof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqenRubmhzZmticXhrd2tieG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTYxNjQsImV4cCI6MjA1ODY3MjE2NH0.PHG9-Gqf98p5XK3sjwAA5YN-qrfcI07Tkc4kPGCuXpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);